### ISSUE TITLE
Change the product relationship types being shown on the PDP pages to be more demo friendly

### ISSUE THREAD

**Issue by PNW14** [websterian/Sitecore.Demo.Retail#12]
Currently showing what the relationship name is from AX and not something retail friendly.

**Comment by websterian** [comment]
You can export the catalog and do a find and replace on the relationship description. I have done this in the demo machine for you.

**Comment by PNW14** [comment]
in the pbMD 8.2 storefront, there's code that will allow changing the labels of the relationships using the content manager.   While the current fix is fine for demoware, we should look at fixing with content overrides for the public version.
