### ISSUE TITLE
Update Merch Manager to use the fixed up version from Product. 

### ISSUE THREAD

**Issue by PNW14** [websterian/Sitecore.Demo.Retail#4]
There's a bug in the released version that blocks MM from seeing image associations on products.  Brandon gave us a new version that fixed it.  I can send over the private build of that one.

**Comment by websterian** [comment]
Flick this over and we will get it in.

**Comment by PNW14** [comment]
[Sitecore Merchandising Manager.8.2.174.zip](https://github.com/websterian/Sitecore.Demo.Retail/files/1333257/Sitecore.Merchandising.Manager.8.2.174.zip)
update file attached

**Comment by PNW14** [comment]
Had to manually change the Sitecore.Commerce.UX.MerchandisingManager.dll to use the older version from 8.2 - Sitecore.Commerce.UX.Merchandising.dll.  Looks like it's working now but has a minor UI glitch that I think needs the old ascx file copied over too.
